### ISSUE TITLE
Fourier feature sampling?

### ISSUE THREAD

**Issue by sihyun-yu** [universome/inr-gan#11]
Hello, thank you for the nice work!

It seems the Fourier feature matrix is "fixed" in current implementation (with a default config) rather than "sampled" for each image, as mentioned in the paper.
Do I misunderstand some details regarding your paper or implementation?

Sincerely,
Sihyun

**Comment by universome** [comment]
Hi, Sihyun! Current implementation indeed uses fixed Fourier feature matrix since it worked just fine in terms of performance (when  [a proper range of frequencies](https://github.com/universome/inr-gan/blob/master/src/training/layers.py#L266) is used) and is faster to compute. You can check the [original implementation](https://github.com/universome/inr-gan/tree/master/archive/original-implementation) where we used the "predictable" ones (i.e. Fourier feature matrix is produced from a latent code). You can also enable the predictable Fourier feature matrix in the current implementation by setting `predictable_emb_size` > 0.

**Comment by sihyun-yu** [comment]
Thank you for detailed response!

**Comment by universome** [comment]
Feel free to ask any further questions!

**Comment by sihyun-yu** [comment]
Hello Ivan,

Could I ask your one more question?
I am trying out to to train INR-GAN on multi-class dataset (e.g., LSUN-10), and is there any specific hyperparameter should be changed or carefully tuned? Or utilizing the same hyperparameter setup is enough?

Thank you In advance!

Sincerely,
Sihyun

**Comment by universome** [comment]
@sihyun-yu 

Hi, Sihyun! I believe that utilizing the same hyperparameter setup should be enough, but note that StyleGAN2-like architectures severely underfit complex multi-class datasets like ImageNet. It is still a mystery to me why this happens. The first 2 things I suspect are constant input (it is easy for SG2 to change styles, but difficult to change the content and move objects around) and R1 regularization (BigGAN showed that it hurts the performance). So if you want to squeeze the best performance out of StyleGAN2 or INR-GAN, it might make sense to play with those. 

When I was training INR-GAN on class-conditional ImageNet 256^2, it performed very similar to StyleGAN2, achieving 44.21 vs 43.0 FID after ~5 days of training on 4 v100 GPUs

**Comment by sihyun-yu** [comment]
I sincerely feel grateful to your kind and detailed response.
I strongly believe your work is wonderful - and many future works would like to build new ideas upon your work regarding designing a new inr-based generative model. I will try out experiments with some different hyperparameter (and share the result if something seems beneficial).

**Comment by universome** [comment]
Thank you for your kind words, don't hesitate to ask any further questions if you'll have any!
