### ISSUE TITLE
Question about the super-resolution

### ISSUE THREAD

**Issue by jihoontack** [universome/inr-gan#14]
Hi Ivan,

Thank you for the wonderful research!
Really enjoyed reading your paper (also, the recent ICCV paper was great!)

While I was reading the paper, I recognize the details for the super-resolution (SR) experiments are somewhat missing.
For me SR was not trivial in INR-GAN as it utilizes MultiScale-INR.
If possible could you share the details of SR experiments? e.g., increasing the resolution of the first input grid...?

If you can share the implementation of SR, it couldn't be better!

Hope you have a nice day,
Jihoon

**Comment by universome** [comment]
Hi, Jihoon! In the original paper, we did [the upsampling](https://github.com/universome/inr-gan/blob/master/archive/original-implementation/src/models/inrs/inrs.py#L508) _after_ [the first multi-scale block](https://github.com/universome/inr-gan/blob/master/archive/original-implementation/configs/inr-gan.yml#L107), but as far as I remember, this choice was quite arbitrary and the model performed more-or-less the same regardless of the block idx you choose to do the upsampling in.

In the current implementation, the superresolution is not implemented, I will take a look at it next week. I believe the most reasonable place to incorporate it is _before_ the first block, i.e. in the [CoordsInput layer](https://github.com/universome/inr-gan/blob/master/src/training/layers.py#L93). But this would require to change some `misc.assert_shape(...)` statements and interpolate static positional embeddings to match the required image size (otherwise, it will fail [here](https://github.com/universome/inr-gan/blob/master/src/training/layers.py#L237)).

**Comment by jihoontack** [comment]
Thank you so much for the detailed response and the clarification!

Best,
Jihoon
