### ISSUE TITLE
model save and load module

### ISSUE THREAD

**Issue by danielkaifeng** [universome/inr-gan#4]
I search all the codes and found there isn't torch.save and load function.
I would add this function and create inference scripts, could you give me some hints?

**Comment by universome** [comment]
Hi! Since `GANTrainer` inherits from firelab's `BaseTrainer`, the checkpointing is being done by firelab [here](https://github.com/universome/firelab/blob/master/firelab/base_trainer.py#L239-L258). Sorry for this confusion, I admit it was a mistake to incorporate firelab into this project. This library was good two years ago when there were no analogs, and I had been constantly thinking that I will find time to do the missing documentation/testing for it to become a decent lib. But now I gave up those delusions and we are rewriting everything into pytorch-lightning. I hope this will make the code more clear.
